### ISSUE TITLE
NoSuchMethodError -> CircuitFabricatorRecipes.addRecipe

### ISSUE THREAD

**Issue by jaz000** [MJRLegends/GalacticraftTweaker#2]
Has something being called in galacticraft changed in the latest version? I can't get anything to add to the Circuit Fabricator, not even the wiki example:

[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <minecraft:emerald> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:repeater> to Output <galacticraftcore:basic_item:14>

[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: Galacticraft.zs}: micdoodle8.mods.galacticraft.api.recipe.CircuitFabricatorRecipes.addRecipe(Lnet/minecraft/item/ItemStack;Lnet/minecraft/util/NonNullList;)V
java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.api.recipe.CircuitFabricatorRecipes.addRecipe(Lnet/minecraft/item/ItemStack;Lnet/minecraft/util/NonNullList;)V
	at com.mjr.galacticrafttweaker.crafttweaker.ActionAddCircuitFabricatorRecipe.apply(ActionAddCircuitFabricatorRecipe.java:35)

potentially relevant versions of things:

forge-1.12.2-14.23.4.2703-universal.jar

GalacticraftCore-1.12.2-4.0.1.177.jar
Galacticraft-Planets-1.12.2-4.0.1.177.jar
MicdoodleCore-1.12.2-4.0.1.177.jar
GalacticraftTweaker-1.12.2-1.0.1.jar

More-Planets-1.12.2-2.0.14-GC156.jar
MorePlanetsExtras-1.12.2-1.0.jar
PlanetProgression-1.12.2-0.2.4.jar
ExtraPlanets-1.12.2-0.3.8.jar

**Comment by MJRLegends** [comment]
Please post a copy of your script file

**Comment by jaz000** [comment]
the above example is just the line from the wiki page

mods.GalacticraftTweaker.addCircuitFabricatorRecipe(<galacticraftcore:basic_item:14>, <minecraft:emerald>, <galacticraftcore:basic_item:2>, <galacticraftcore:basic_item:2>, <minecraft:redstone>, <minecraft:repeater>);

My actual goal is a number of lines like this below which gives the same (just reducing number of output, although I'd like to add some other items to the fabricator as well).

mods.GalacticraftTweaker.removeCrircuitFabricatorRecipe(<extraplanets:wafer>);
mods.GalacticraftTweaker.addCircuitFabricatorRecipe(<extraplanets:wafer>, 
	<minecraft:diamond>, <galacticraftcore:basic_item:2>, <galacticraftcore:basic_item:2>, <galacticraftplanets:mars:9>, <minecraft:redstone_lamp>);

**Comment by MJRLegends** [comment]
Your missing the <> round each item/itemstack see examples 

`mods.GalacticraftTweaker.addCircuitFabricatorRecipe(<galacticraftcore:basic_item:14>, <minecraft:emerald>, <galacticraftcore:basic_item:2>, <galacticraftcore:basic_item:2>, <minecraft:redstone>, <minecraft:repeater>);`

**Comment by jaz000** [comment]
this is my entire script (these parts commented out)
https://pastebin.com/3FcA3PUr

I think GitHub ate my <>'s on submit

**Comment by MJRLegends** [comment]
Please show me your defo using v1.0.1 of GalacticraftTweaker

**Comment by jaz000** [comment]
yes - header from the forge log showing all mods:
https://pastebin.com/AzT4ZKhV

date on the file is 16/04 - a while ago- I can re-download to be sure ...

**Comment by jaz000** [comment]
Yeah sorry - I re-downloaded from curse and the problem is still in happening - and I saw the changelog for that version as well so I see why you asked ...

**Comment by MJRLegends** [comment]
Idk then sorry, works all ok for me

```
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: Main.zs}
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <galacticraftcore:basic_item:14>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <minecraft:emerald> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:repeater> to Output <galacticraftcore:basic_item:14>
[INITIALIZATION][CLIENT][INFO] Adding Compressor Recipe: Input 1 <minecraft:emerald> Input 2 null Input 3 null Input 4 null Input 5 null Input 6 null Input 7 null Input 8 null Input 9 null to Output <galacticraftcore:basic_item:14>
[INITIALIZATION][CLIENT][INFO] Removing Compressor Recipe: for Output <galacticraftcore:basic_item:6>
[INITIALIZATION][CLIENT][INFO] Adding Block Smasher Recipe: Input <minecraft:cobblestone> to Output <minecraft:stone>
[INITIALIZATION][CLIENT][INFO] Removing Block Smasher Recipe: Output<extraplanets:potash_shards> * 3
[INITIALIZATION][CLIENT][INFO] Adding Solar Evaporation Chamber Recipe: Input <minecraft:stone> to Output <minecraft:cobblestone>
[INITIALIZATION][CLIENT][INFO] Removing Solar Evaporation Chamber Recipe: Output<extraplanets:potassium>
[INITIALIZATION][CLIENT][INFO] Replacing SpaceStation recipe for station with id: -27 Input 1 <minecraft:emerald> * 6 Input 2 <galacticraftcore:basic_item:2> * 24 Input 3 <minecraft:redstone> * 12 Input 4 null Input 5 
```

Here is my script file if it helps 

Ignore the ExtraPlanets entries that just because i test them both together to check for any issues
```
mods.GalacticraftTweaker.removeCircuitFabricatorRecipe(<galacticraftcore:basic_item:14>);
mods.GalacticraftTweaker.addCircuitFabricatorRecipe(<galacticraftcore:basic_item:14>, <minecraft:emerald>, <galacticraftcore:basic_item:2>, <galacticraftcore:basic_item:2>, <minecraft:redstone>, <minecraft:repeater>);
mods.GalacticraftTweaker.addCompressorShapelessRecipe(<galacticraftcore:basic_item:14>,<minecraft:emerald>, null, null, null, null, null, null, null, null);
mods.GalacticraftTweaker.removeCompressorRecipe(<galacticraftcore:basic_item:6>);

mods.ExtraPlanets.addBlockSmasherRecipe(<minecraft:stone>, <minecraft:cobblestone>);
mods.ExtraPlanets.removeBlockSmasherRecipe(<extraplanets:potash_shards> * 3);

mods.ExtraPlanets.addSolarEvaporationChamberRecipe(<minecraft:cobblestone>, <minecraft:stone>);
mods.ExtraPlanets.removeSolarEvaporationChamberRecipe(<extraplanets:potassium>);

mods.GalacticraftTweaker.modifySpaceStationRecipe(-27, <minecraft:emerald> * 6, <galacticraftcore:basic_item:2> * 24, <minecraft:redstone> * 12);
```

**Comment by MJRLegends** [comment]
I'll give your recipe changes your trying to make a test in my setup and see if something is wrong there

**Comment by MJRLegends** [comment]
Yeah all seems good

**Comment by MJRLegends** [comment]
Here is my script file if it helps 

Ignore the ExtraPlanets entries that just because i test them both together to check for any issues
```
mods.GalacticraftTweaker.removeCircuitFabricatorRecipe(<galacticraftcore:basic_item:14>);
mods.GalacticraftTweaker.addCircuitFabricatorRecipe(<galacticraftcore:basic_item:14>, <minecraft:emerald>, <galacticraftcore:basic_item:2>, <galacticraftcore:basic_item:2>, <minecraft:redstone>, <minecraft:repeater>);
mods.GalacticraftTweaker.addCompressorShapelessRecipe(<galacticraftcore:basic_item:14>,<minecraft:emerald>, null, null, null, null, null, null, null, null);
mods.GalacticraftTweaker.removeCompressorRecipe(<galacticraftcore:basic_item:6>);

mods.ExtraPlanets.addBlockSmasherRecipe(<minecraft:stone>, <minecraft:cobblestone>);
mods.ExtraPlanets.removeBlockSmasherRecipe(<extraplanets:potash_shards> * 3);

mods.ExtraPlanets.addSolarEvaporationChamberRecipe(<minecraft:cobblestone>, <minecraft:stone>);
mods.ExtraPlanets.removeSolarEvaporationChamberRecipe(<extraplanets:potassium>);

mods.GalacticraftTweaker.modifySpaceStationRecipe(-27, <minecraft:emerald> * 6, <galacticraftcore:basic_item:2> * 24, <minecraft:redstone> * 12);
```

**Comment by MJRLegends** [comment]
Here is the log for your script you provide me, i corrected a few spelling errors you had with removeCircuitFabricatorRecipe and addCircuitFabricatorRecipe
```

[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: Main.zs}
[INITIALIZATION][CLIENT][ERROR] Main.zs:17: Could not resolve <techreborn : ingot : 14>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <galacticraftcore:basic_item:14>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <minecraft:diamond> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:redstone_torch> to Output <galacticraftcore:basic_item:14> * 2
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <galacticraftcore:basic_item:13>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <minecraft:diamond> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:repeater> to Output <galacticraftcore:basic_item:13>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <extraplanets:wafer>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <minecraft:diamond> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <galacticraftplanets:mars:9> Input 5 <minecraft:redstone_lamp> to Output <extraplanets:wafer>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <extraplanets:wafer:2>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <galacticraftplanets:item_basic_asteroids> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:redstone_torch> to Output <extraplanets:wafer:2>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 null Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:redstone_torch> to Output <extraplanets:wafer:2>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <extraplanets:wafer:3>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <extraplanets:tier5_items:8> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <galacticraftplanets:mars:9> Input 5 <minecraft:repeater> to Output <extraplanets:wafer:3>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <extraplanets:wafer:4>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <extraplanets:tier8_items:6> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <galacticraftplanets:mars:9> Input 5 <minecraft:repeater> to Output <extraplanets:wafer:4>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <extraplanets:wafer:5>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <extraplanets:tier7_items:7> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <galacticraftplanets:mars:9> Input 5 <minecraft:repeater> to Output <extraplanets:wafer:5>
[INITIALIZATION][CLIENT][INFO] Removing CircuitFabricator Recipe: With Output <extraplanets:wafer:1>
[INITIALIZATION][CLIENT][INFO] Adding CircuitFabricator Recipe: Input 1 <extraplanets:tier4_items:5> Input 2 <galacticraftcore:basic_item:2> Input 3 <galacticraftcore:basic_item:2> Input 4 <minecraft:redstone> Input 5 <minecraft:repeater> to Output <extraplanets:wafer:1>

```

**Comment by jaz000** [comment]
Very strange

I don't suppose you could share the modlist/versions you are testing with?

I'm down to 9 mods and still getting the error

Adding a compressor recipe is working fine ...

**Comment by MJRLegends** [comment]
i think i know the issue will be fixed for the next update @jaz000 @EngineerXL

**Comment by MJRLegends** [comment]
Fixed version has been uploaded to curseforge

**Comment by EngineerXL** [comment]
Ty. I was finally able to get this across to you.
